### ISSUE TITLE
missing option for custom template

### ISSUE THREAD

**Issue by madhur4127** [horcrux2301/AFCP#1]
This plugin is very helpful, but I how can I add a file to every problem folder while it is parsed? I use "ip.txt" as input file and I have configured with atom comfortably for running test case manually.

I want to create that file in the problem folder when I parse contest.

Thanks for this amazing plugin.

**Comment by horcrux2301** [comment]
So you want a custom name option(like in settings?) for the input file that the package parses?

**Comment by madhur4127** [comment]
No, I want to generate an extra file in every folder while contest is parse , instead of manually creating for problems.
