### ISSUE TITLE
Notification of 'diff' rather than output files

### ISSUE THREAD

**Issue by madhur4127** [horcrux2301/AFCP#2]
Consider a problem with long output like 8-10 lines, in order to verify my output and correct output I have to drag both the files side by side and then compare it. It is time consuming and defies the purpose of this plugin. 

**Suggested Alternative:** You may add notification of evaluation of test case, rather than output the file. It will solve the purpose as all I will need to know is that whether I passed the test case or not rather than the output.
You may use `diff` as a tool to enhance the scheme I proposed. Consider:
```
000  ---> 0 0 0
123  ---> 1 2 3
123  ---> 1 2 3
```
Though output seems similar but there will be wrong answer because of spaces between digits. Using `diff` will solve the problem, and also highlight the differences.

**Comment by horcrux2301** [comment]
I will work on this. 👍🏻

**Comment by horcrux2301** [comment]
Which OS are you using?

**Comment by madhur4127** [comment]
Linux Mint 18.3

**Comment by madhur4127** [comment]
Hey, I have found some good plugin avilable in other editor for reference.
1.  [Vim: CFParser](https://github.com/gabrielsimoes/cfparser.vim)
2. [Emacs: CFParser](https://github.com/gnull/cfparser)

**Comment by horcrux2301** [comment]
Which feature in these parsers are you particularly interested in? 

I worked on the diff feature but I am having a problem with showing the added and removed parts in proper colors in a diff file. 

I am looking for a hack around that.

**Comment by madhur4127** [comment]
Atom already has git diff in it, using it differences can be generated easily from two files [using this](https://ibb.co/dvYaUJ). Also `git dif a a` produces no output so it can be easily checked for correct results. 

But diff will produce unwanted errors too `10.23 != 10.2300` and `11111111112 == 11111111113` in terms of relative error, and it will create issues. Using existing checker will help instead of inventing the wheel.

Submission of current file is a noteworthy feature is of the parsers.

There's another tool 'HighTail' by dj3500 which uses a cool checker which has (precision check too with relative error).

**Comment by horcrux2301** [comment]
Hey @madhur4127 ,

Thanks for your inputs.

I have published an update that has the diff feature. To get the diff use the key combination `ctrl+alt+p` to open a pane showing the diff between files. 

Note that this will only show diffs between files starting with names `output*` and  `myOutput*`. For eg:- `output1.txt` and `myOutput1.txt`

Please use this and report bugs, if any.  🙂

Note that this is the first iteration. Next up is notifications for the diffs generated.

**Comment by horcrux2301** [comment]
@madhur4127 Notifications based on diffs generated is released in version `0.8.18`.
